"""
Data source abstraction.

The demo loads sellers from CSVs generated by Faker. In enterprise deployment
sellers come from the marketplace's system of record: could be a Postgres/MySQL
DB, a REST API, a warehouse (Snowflake/BigQuery), or Kafka change events.

This module defines the abstract `SellerDataSource` protocol and provides
concrete adapters. Services and models take the protocol as a dependency, not
a concrete class, so swapping sources is a config change.

For freshness, wrap the source in `CachedSellerDataSource` which uses Redis
with a TTL. For very large tenants, use `IncrementalSellerDataSource` which
pulls only changed rows since a watermark.
"""
from __future__ import annotations

import time
from dataclasses import dataclass
from datetime import datetime
from typing import Iterator, Protocol

import pandas as pd
from sqlalchemy import text
from sqlalchemy.engine import Engine


@dataclass(frozen=True)
class SellerRecord:
    """Canonical seller schema exposed to services. Any adapter must map its
    source-specific schema to this."""
    seller_id: str
    tenant_id: str
    company_name: str
    category: str
    country: str
    region: str
    monthly_revenue: float
    orders: int
    avg_order_value: float
    return_rate: float
    customer_rating: float
    late_shipment_pct: float
    cancellation_pct: float
    ad_spend: float
    conversion_rate: float
    seller_age_months: int
    growth_rate: float
    repeat_customer_pct: float
    account_manager_id: str | None
    last_contact_date: datetime | None
    support_tickets: int
    seller_tier: str


class SellerDataSource(Protocol):
    def list_sellers(self, tenant_id: str, *, limit: int | None = None,
                     since: datetime | None = None) -> Iterator[SellerRecord]: ...

    def get_seller(self, tenant_id: str, seller_id: str) -> SellerRecord | None: ...

    def health_check(self) -> bool: ...


# ---------------------------------------------------------------------------
# Adapter 1: Marketplace SQL database (the enterprise default)
# ---------------------------------------------------------------------------
class SQLSellerDataSource:
    """Reads sellers from a marketplace system-of-record database via a
    parameterized SQL view. The view is provided by the marketplace team — this
    adapter is deliberately thin over it so schema changes there don't ripple
    into service code.

    The view must project columns matching SellerRecord fields."""

    def __init__(self, engine: Engine, view_name: str = "vw_sellers_canonical"):
        self._engine = engine
        self._view = view_name

    def list_sellers(self, tenant_id: str, *, limit=None, since=None) -> Iterator[SellerRecord]:
        query = f"SELECT * FROM {self._view} WHERE tenant_id = :tid"
        params = {"tid": tenant_id}
        if since is not None:
            query += " AND updated_at >= :since"
            params["since"] = since
        if limit is not None:
            query += " LIMIT :limit"
            params["limit"] = limit

        with self._engine.connect() as conn:
            result = conn.execution_options(stream_results=True).execute(text(query), params)
            for row in result.mappings():
                yield self._row_to_record(row)

    def get_seller(self, tenant_id: str, seller_id: str) -> SellerRecord | None:
        query = f"SELECT * FROM {self._view} WHERE tenant_id = :tid AND seller_id = :sid"
        with self._engine.connect() as conn:
            row = conn.execute(text(query), {"tid": tenant_id, "sid": seller_id}).mappings().first()
        return self._row_to_record(row) if row else None

    def health_check(self) -> bool:
        try:
            with self._engine.connect() as conn:
                conn.execute(text("SELECT 1"))
            return True
        except Exception:
            return False

    @staticmethod
    def _row_to_record(row) -> SellerRecord:
        return SellerRecord(**{k: row[k] for k in SellerRecord.__annotations__ if k in row})


# ---------------------------------------------------------------------------
# Adapter 2: REST API (for marketplaces that expose seller data via API)
# ---------------------------------------------------------------------------
class RESTSellerDataSource:
    """For marketplaces where sellers are exposed via REST. Uses cursor-based
    pagination; expects the API to be idempotent and rate-limited.

    Retries with exponential backoff on 5xx / 429."""

    def __init__(self, base_url: str, api_key: str, timeout_seconds: int = 20,
                 max_retries: int = 3):
        import httpx
        self._client = httpx.Client(
            base_url=base_url,
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=timeout_seconds,
        )
        self._max_retries = max_retries

    def list_sellers(self, tenant_id: str, *, limit=None, since=None) -> Iterator[SellerRecord]:
        cursor = None
        pulled = 0
        while True:
            params = {"tenant_id": tenant_id}
            if cursor:
                params["cursor"] = cursor
            if since:
                params["since"] = since.isoformat()

            resp = self._request_with_retry("GET", "/v1/sellers", params=params)
            page = resp.json()
            for item in page.get("items", []):
                yield SellerRecord(**item)
                pulled += 1
                if limit and pulled >= limit:
                    return
            cursor = page.get("next_cursor")
            if not cursor:
                return

    def get_seller(self, tenant_id: str, seller_id: str) -> SellerRecord | None:
        resp = self._request_with_retry(
            "GET", f"/v1/sellers/{seller_id}", params={"tenant_id": tenant_id}, ok_404=True
        )
        if resp.status_code == 404:
            return None
        return SellerRecord(**resp.json())

    def health_check(self) -> bool:
        try:
            r = self._client.get("/v1/health")
            return r.status_code == 200
        except Exception:
            return False

    def _request_with_retry(self, method: str, path: str, *, ok_404: bool = False, **kwargs):
        last_exc = None
        for attempt in range(self._max_retries + 1):
            try:
                r = self._client.request(method, path, **kwargs)
                if ok_404 and r.status_code == 404:
                    return r
                if r.status_code < 500 and r.status_code != 429:
                    r.raise_for_status()
                    return r
                # transient — back off
            except Exception as exc:
                last_exc = exc
            time.sleep(min(2 ** attempt, 8))
        if last_exc:
            raise last_exc
        raise RuntimeError("REST source exhausted retries")


# ---------------------------------------------------------------------------
# Adapter 3: CSV (dev / demo mode)
# ---------------------------------------------------------------------------
class CSVSellerDataSource:
    """Dev-only adapter matching the demo behavior. Not for prod use."""

    def __init__(self, csv_path: str, default_tenant_id: str):
        self._df = pd.read_csv(csv_path)
        self._tenant = default_tenant_id

    @staticmethod
    def _row_to_record(row, tenant_id: str) -> SellerRecord:
        return SellerRecord(
            seller_id=str(row["seller_id"]),
            tenant_id=tenant_id,
            company_name=str(row.get("company_name", "")),
            category=str(row.get("category", "")),
            country=str(row.get("country", "")),
            region=str(row.get("state", "")),
            monthly_revenue=float(row.get("monthly_revenue", 0)),
            orders=int(row.get("orders", 0)),
            avg_order_value=float(row.get("avg_order_value", 0)),
            return_rate=float(row.get("return_rate", 0)),
            customer_rating=float(row.get("customer_rating", 0)),
            late_shipment_pct=float(row.get("late_shipment_pct", 0)),
            cancellation_pct=float(row.get("cancellation_pct", 0)),
            ad_spend=float(row.get("ad_spend", 0)),
            conversion_rate=float(row.get("conversion_rate", 0)),
            seller_age_months=int(row.get("seller_age_months", 0)),
            growth_rate=float(row.get("growth_rate", 0)),
            repeat_customer_pct=float(row.get("repeat_customer_pct", 0)),
            account_manager_id=row.get("account_manager"),
            last_contact_date=None,
            support_tickets=int(row.get("support_tickets", 0)),
            seller_tier=str(row.get("seller_tier", "standard")),
        )

    def list_sellers(self, tenant_id: str, *, limit=None, since=None) -> Iterator[SellerRecord]:
        df = self._df
        if limit:
            df = df.head(limit)
        for _, row in df.iterrows():
            yield self._row_to_record(row, tenant_id)

    def get_seller(self, tenant_id: str, seller_id: str) -> SellerRecord | None:
        # NOTE: previously this looked up `match` correctly but then discarded
        # it and returned `next(iter(self.list_sellers(...)))` instead — i.e.
        # always the *first* row of the whole file regardless of which
        # seller_id was requested. Fixed to actually build the record from
        # the matched row.
        match = self._df[self._df["seller_id"].astype(str) == seller_id]
        if match.empty:
            return None
        return self._row_to_record(match.iloc[0], tenant_id)

    def health_check(self) -> bool:
        return not self._df.empty
